export enum COMMISSION {
    FLIGHT_ONEWAY = "ONE_WAY",
    FLIGHT_ONEWAY_INTERNATIONAL = "ONE_WAY_INTERNATIONAL",
    ROUND_TRIP = "ROUND_TRIP",
    ROUND_TRIP_INTERNATIONAL = "ROUND_TRIP_INTERNATIONAL",
    MULTICITY = "MULTICITY",
    MULTICITY_INTERNATIONAL = "MULTICITY_INTERNATIONAL",
    HOTEL_DOMESTIC = "HOTEL_DOMESTIC",
    HOTEL_INTERNATIONAL = "HOTEL_INTERNATIONAL"
}
